apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base/postgres.yaml
- ../../base/backend.yaml
- ../../base/frontend.yaml

namespace: trailer-rent-dev

patchesStrategicMerge:
- patches/ingress-patch.yaml

images:
- name: ghcr.io/bleetmaa/trailer-rent-backend
  newTag: dev-latest
- name: ghcr.io/bleetmaa/trailer-rent-frontend  
  newTag: dev-latest
