apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: trailer-rent-prod

resources:
- ../../base

patches:
- path: patches/ingress-patch.yaml

configMapGenerator:
- name: app-config
  literals:
  - DATABASE_NAME=trailerrent_prod
  - ENVIRONMENT=Production
  - API_URL=https://trailerrent.se/api

images:
- name: backend-image
  newName: ghcr.io/bleetmaa/trailer-rent-backend
  newTag: latest
- name: frontend-image
  newName: ghcr.io/bleetmaa/trailer-rent-frontend
  newTag: latest
