apiVersion: batch/v1
kind: Job
metadata:
  name: setup-storage-job
  namespace: default
spec:
  template:
    spec:
      hostNetwork: true
      hostPID: true
      containers:
      - name: setup-storage
        image: alpine:latest
        command: ["/bin/sh"]
        args:
          - -c
          - |
            echo "Creating storage directory on host..."
            mkdir -p /host/mnt/kubernetes-storage/postgres
            chmod 777 /host/mnt/kubernetes-storage/postgres
            ls -la /host/mnt/kubernetes-storage/
            echo "Storage directory created successfully!"
        securityContext:
          privileged: true
        volumeMounts:
        - name: host-root
          mountPath: /host
      volumes:
      - name: host-root
        hostPath:
          path: /
      restartPolicy: OnFailure
      nodeSelector:
        kubernetes.io/hostname: k8s-worker
