apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- backend.yaml
- frontend.yaml
- postgres.yaml
- ingress.yaml

images:
- name: backend-image
  newName: ghcr.io/bleetmaa/trailer-rent-backend
  newTag: latest
- name: frontend-image
  newName: ghcr.io/bleetmaa/trailer-rent-frontend
  newTag: latest
